### ISSUE TITLE
Upvoting Yaks fails

### ISSUE THREAD

**Issue by philiparpin** [akashlevy/Yaklient#8]
When I try to upvote a yak, it fails.

**Comment by akashlevy** [comment]
Can you tell me what the response you are receiving is?

**Comment by philiparpin** [comment]
The upvote_yak function in tools.py returns 'fail'.

**Comment by akashlevy** [comment]
Can you show me the code you are using?

**Comment by akashlevy** [comment]
Is the following code working for you?

```
# Import client classes from Yaklient
from yaklient import *

# Specify location of University of Exeter on a map
exeter = Location(50.7365, -3.5344)

# Create user object at University of Exeter with given userid
user = User(exeter, "21C6CA60E3AA43C4B8C18B943394E111")

# Get yaks, iterate through them, and print them
for yak in user.get_yaks():
    print yak
```

**Comment by philiparpin** [comment]
Yes I can successfully get Yaks. The above code works perfectly. I will send you the code I am using to upvote.

**Comment by philiparpin** [comment]
```
def get_messages(time):
    """Gets messages"""
    b = 0
    oxford = Location(33.6192, -83.8711)
    user = User(oxford)
    for x in user.get_yaks(location=oxford, basecamp=False):
        if b == 0:
            s = user.get_yak(x)
            print s
            print user.upvote_yak(x.message_id)
            print user.post_yak("Hello World! OF OXFORDIANSSSS")
            upvoter(x.message_id, 30)
            b = b + 1
            print s

get_messages(30)

```

**Comment by philiparpin** [comment]
The above code doesn't work

**Comment by akashlevy** [comment]
Right now posting is not working using the Yaklient library: the API has changed such that posting requires phone verification now as you may have noticed within the app. Sorry!

As for the fact that user.upvote_yak(x.message_id) is not working:
Upvoting using upvote_yak will not work immediately, because Yik Yak has a 60 second timeout after creating a user before you can upvote anything. For this reason, I created the upvoter method which bypasses this timeout by creating users, waiting for a certain amount of time, then upvoting. Use this instead.

Hope this helps! Let me know if you have any other issues.

**Comment by akashlevy** [comment]
Also please star my library if you found it useful! :)
